<?php

namespace Tests\Unit;

use App\services\ServicioService;
use App\services\SocioService;
use Tests\TestCase;
use Illuminate\Foundation\Testing\DatabaseMigrations;
use Illuminate\Foundation\Testing\DatabaseTransactions;

class EntradaTest extends TestCase
{
    use DatabaseMigrations;

    private $service;
    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->service = new SocioService();
        $this->servService = new ServicioService();
        $this->artisan('migrate', ['--database' => 'mysql_testing']);
        $this->artisan('db:seed', ['--class' => 'SocioSeeder', '--database' => 'mysql_testing']);

    }

    public function testAccederAUnaHoraDondeSoloHayaUnServicioDisponible()
    {

    }

    public function testAccederAUnaHoraDondeHayaMasDeUnServicioDisponible()
    {

    }

    public function testAccederAUnaHoraDondeNoHayaServiciosDisponibles()
    {

    }

    public function testAccederAUnaHoraDondeHayaUnServicioSinCreditos()
    {

    }

    public function testAccederAUnaHoraDondeElServicioEsteVencido()
    {

    }
}
