<?php

namespace Tests\Unit;

use App\services\VendibleService;
use Tests\TestCase;
use Illuminate\Foundation\Testing\DatabaseMigrations;
use Illuminate\Foundation\Testing\DatabaseTransactions;

class VendibleServiceTest extends TestCase
{
    use DatabaseMigrations;


    private $service;
    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->service = new VendibleService();

    }
    public function testAllClases()
    {

        factory(\App\Clase::class)->create();
        factory(\App\Clase::class)->create();
        factory(\App\Clase::class)->create();

        factory(\App\Articulo::class)->create();
        factory(\App\Articulo::class)->create();
        factory(\App\Articulo::class)->create();


        $clases = $this->service->clases();

        $this->assertEquals($clases->count(), 3);

    }
    public function testAllArticulos()
    {

        factory(\App\Clase::class)->create();
        factory(\App\Clase::class)->create();
        factory(\App\Clase::class)->create();

        factory(\App\Articulo::class)->create();
        factory(\App\Articulo::class)->create();
        factory(\App\Articulo::class)->create();


        $articulos = $this->service->articulos();

        $this->assertEquals($articulos->count(), 3);

    }
}
